# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"@\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\tsent_time\x18\x02 \x01(\t\x12\x11\n\trecipient\x18\x03 \x01(\t\"1\n\x0b\x43redentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"!\n\x07Request\x12\x16\n\x0erequest_status\x18\x01 \x01(\x05\"\'\n\rMessageStatus\x12\x16\n\x0emessage_status\x18\x01 \x01(\x05\"&\n\rAccountStatus\x12\x15\n\rAccountStatus\x18\x01 \x01(\x08\x32\xe9\x01\n\x0b\x43hatService\x12&\n\x08getUsers\x12\x08.Request\x1a\x0c.Credentials\"\x00\x30\x01\x12\"\n\x08getInbox\x12\x08.Request\x1a\x08.Message\"\x00\x30\x01\x12\x31\n\rCreateAccount\x12\x0c.Credentials\x1a\x0e.AccountStatus\"\x00(\x01\x12*\n\x08SendChat\x12\x08.Message\x1a\x0e.MessageStatus\"\x00(\x01\x30\x01\x12/\n\rDeleteAccount\x12\x0c.Credentials\x1a\x0e.AccountStatus\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=14
  _MESSAGE._serialized_end=78
  _CREDENTIALS._serialized_start=80
  _CREDENTIALS._serialized_end=129
  _REQUEST._serialized_start=131
  _REQUEST._serialized_end=164
  _MESSAGESTATUS._serialized_start=166
  _MESSAGESTATUS._serialized_end=205
  _ACCOUNTSTATUS._serialized_start=207
  _ACCOUNTSTATUS._serialized_end=245
  _CHATSERVICE._serialized_start=248
  _CHATSERVICE._serialized_end=481
# @@protoc_insertion_point(module_scope)
